service: recipe-app-graphql
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

plugins:
  - serverless-offline

package:
  exclude:
    - "**/*.test.js"

functions:
  graphql:
    handler: src/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
