version: 2
jobs:
  build_server:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/recipe-app/server

    steps:
      - checkout: &checkout
          path: ~/recipe-app

      - restore_cache: &installation_cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: make install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: make test
      - run: make lint

  deploy:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/recipe-app/server

    steps:
      - checkout: *checkout
      - restore_cache: *installation_cache
      - run: make deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_server
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
