version: 2
jobs:
  build_server:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/recipe-app/server

    steps:
      - checkout: &checkout
          path: ~/recipe-app

      - restore_cache: &server_installation_cache
          keys:
            - v2-server-dependencies-{{ checksum "package.json" }}
            - v2-server-dependencies-

      - run: make install

      - save_cache:
          paths:
            - node_modules
          key: v2-server-dependencies-{{ checksum "package.json" }}

      - run: make test
      - run: make lint

  build_client:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/recipe-app/client

    steps:
      - checkout: &checkout
          path: ~/recipe-app

      - restore_cache: &client_installation_cache
          keys:
            - v2-client-dependencies-{{ checksum "package.json" }}
            - v2-client-dependencies-

      - run: make install

      - save_cache:
          paths:
            - node_modules
          key: v2-client-dependencies-{{ checksum "package.json" }}

      - run: make test
      - run: make lint

  deploy:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/recipe-app

    steps:
      - checkout: *checkout
      - restore_cache: *server_installation_cache
      - run: cd server && make deploy
      - restore_cache: *client_installation_cache
      - run: cd client && make deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_server
      - build_client
      - deploy:
          requires:
            - build_server
            - build_client
          filters:
            branches:
              only: master
