version: 2.1

jobs:
  test_server:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/recipe-app/server

    steps:
      - checkout: &checkout
          path: ~/recipe-app

      - restore_cache:
          keys:
            - v2-server-dependencies-{{ checksum "package.json" }}
            - v2-server-dependencies-

      - run: make install

      - save_cache:
          paths:
            - node_modules
          key: v2-server-dependencies-{{ checksum "package.json" }}

      - run: make test
      - run: make lint

  test_client:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/recipe-app/client

    steps:
      - checkout: &checkout
          path: ~/recipe-app

      - restore_cache:
          keys:
            - v2-client-dependencies-{{ checksum "package.json" }}
            - v2-client-dependencies-

      - run: make install

      - save_cache:
          paths:
            - node_modules
          key: v2-client-dependencies-{{ checksum "package.json" }}

      - run: make test
      - run: make lint

  deploy:
    docker:
      - image: travnels/circleci-nodejs-awscli:latest

    working_directory: ~/recipe-app

    steps:
      - checkout: *checkout

      - restore_cache:
          keys:
            - v2-server-dependencies-{{ checksum "server/package.json" }}

      - run: cd server && ENVIRONMENT=production make deploy

      - restore_cache:
          keys:
            - v2-client-dependencies-{{ checksum "client/package.json" }}

      - run: cd client && ENVIRONMENT=production make deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test_server
      - test_client
      - deploy:
          requires:
            - test_server
            - test_client
          filters:
            branches:
              only: master
